### PR TITLE
Switching from 'glossary' package to 'glossaries', from '\include' to '\input' and correcting the README file

### PR DESCRIPTION
**Pull request by tassos**
I made three commits, each fixing one of the following:

- I changed all the \include commands in favour of \input, as it allows nesting two levels of files. Therefore it is possible to \input tables or other files inside each chapter.
- I switched from the 'glossary' package to the newer 'glossaries'
- I fixed a small problem with the README file and the 'prelim/tothejury' options of the class

### CODE REVIEW

**Comment by tassos** [comment]
Hey, any plans on merging these changes? If not, I can cancel the pull request.

**Comment by wannesm** [comment]
It took some extra refactoring (no default xindy, different call to include glossary, ...) but all of the suggestions except include/input have been included in the master release.

**Comment by tassos** [comment]
Thanks for taking care of this. May I ask why did you decide not to accept the include/input suggestion? Just curious.

**Comment by wannesm** [comment]
The include command is faster and has more options (e.g. per chapter compilation). Also the include command does not prohibit one to use a nested \input . You can do for example `\input{chapters/introduction/test.tex}` in the file `chapters/introduction/introduction.tex` and it will include the referred to file. It's true that you can't do a nested \include but that's not a problem.

**Comment by tassos** [comment]
Okay, that is interesting. I didn't know you could use \input inside \included files. Thanks for the clarification!

**Pull request closed without merging**
